# Generated by Django 3.0.7 on 2023-01-19 10:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 10, 36, 59, 89865)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.CharField(choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
