# Generated by Django 3.0.6 on 2023-01-19 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20230119_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 12, 57, 54, 101245)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='features',
            field=models.CharField(choices=[('Cruise control', 'Cruise control'), ('Airbags', 'Airbags'), ('Audio Interface', 'Audio Interface')], max_length=100),
        ),
    ]
