# Generated by Django 3.0.6 on 2023-01-19 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20230119_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 13, 16, 17, 186824)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
