# Generated by Django 3.0.6 on 2023-01-19 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_auto_20230119_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 19, 13, 24, 2, 816207)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=10),
        ),
    ]
